name: testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install requirements
      run: |
          brew install graphviz ninja doxygen
    - name: configure
      run: cmake -G Ninja -B ./build -S .
    - name: build
      run: cmake --build build -t doc

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
      
    - uses: actions/checkout@v2
      name: Check out code
      
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker Image
      with:
        image: zepferc/test
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
